### ISSUE TITLE
Make the installer less prominent

### ISSUE THREAD

**Issue by supriyo-biswas** [MoonchildProductions/PM4Linux-installer#27]
The Linux homepage goes makes a big deal of the installer, with it having its own install page and even release notes! The installer is also wrapped in a bzip2 tarball, which AFAICT serves no purpose either. However, it does give the appearance of complexity to the installation procedure, even though there is very little of it in reality.

I'd suggest not making the installer so prominent, since it is just a throwaway tool. Simply state something along the lines of this on the homepage:

---

### Installation

You can install Pale Moon by downloading and running the installation script:

    wget http://linux.palemoon.org/installer
    bash installer

Simply rerun these steps if you want to uninstall or update Pale Moon.

If automated installers aren't your thing, you can download the binaries(Link to binaries). You can also use the following repositories to install it:
(...)

---

In the above example,  http://linux.palemoon.org/installer points to a current build of the pminstaller.sh script that goes into the archive.

**Comment by trav90** [comment]
I agree that the installer should begin to be less prominent on the Linux site. I'll make some changes accordingly.

**Comment by trav90** [comment]
Off hand, here's a few things that could be done:

- [ ] Move the release notes to GitHub (there's no real reason to leave them on the Linux site when they can be added to the repo IMO).
- [ ] As stated above, we can add a small blurb to the homepage containing a download link and checksum/sig information for those who want it instead of using an entire dedicated page.
- [ ] The notes contained on the current download page are already included in /userdocs/README. Having them on both the website and included in the downloaded tarball seems redundant.

@wolfbeast @mattatobin what do you guys think?

**Comment by wolfbeast** [comment]
Sounds like a good plan except the last point - a readme in userdocs isn't discoverable, and having information available BEFORE downloading is generally preferred. It's not redundant, therefore, but depending on how much and how technical the readme is, you could relocate the info to an appropriate place.

**Comment by trav90** [comment]
/userdocs is where the readme is located in the repo, not the final tarball we offer for download. By redundant I was referring to the fact that the readme is extracted alongside the installer script as well as being viewable from within the installer itself (using the "View readme" option), in addition to being on the download page. Maybe we should leave the download page as-is and remove the bundled readme from the tarball instead.

**Comment by supriyo-biswas** [comment]
It seems to me that the only reason a README is required is due to the installer being so complicated and GUI-based. So,

* Is there a reason for the tool to be GUI based?
* Can the current tool be replaced with a CLI script?

Replacing the script would make it far simpler; eliminate the need for having a README and help with automated installs and headless environments.

**Comment by wolfbeast** [comment]
Having the README available from the installer is still a good thing IMHO. I would not remove it. It's common practice to have important "read me" information available both on-site and in downloaded software. Like I said it's _not_ redundant.

It's GUI based because it's assumed people are installing it from a GUI (desktop) to be used in a GUI. You can't use Pale Moon headless and I certainly don't see a point in pushing GUI-using Linux users to using the terminal when they don't have to -- currently people can do everything in their graphical environment to install and use Pale Moon. In addition, it would complicate integration with DEs because you'd have to somehow figure out what you're running in without running in it.

Besides, people who want to install it headless anyway can just as easily use wget+tar to get the bzipped tarball and install it that way.

**Comment by mattatobin** [comment]
I think it should be left as-is.

**Comment by trav90** [comment]
After sleeping on it, I think that at this point things should stay as they are. We can revisit this issue at some point in the future once we have a better solution (be it a new installer or use the internal updater or whatever).

Closing for now.
